### ISSUE TITLE
Failed to compile in Mac OS X 10.8.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lanzen/ampliconnoise#20]
```
I get this message when I tried to compile AN 1.28. Ideas?

gdemac:AmpliconNoiseV1.28 charlie$ make
(cd FCluster && make)
cc -O3 -c FCluster.c 
FCluster.c:223:1: warning: type specifier missing, defaults to 'int' 
[-Wimplicit-int]
UpdateMinCacheForMarkedRows(struct t_Min* asMin,float** aafDistMatrix,int nN)
^~~~~~~~~~~~~~~~~~~~~~~~~~~
FCluster.c:230:13: warning: implicit declaration of function 
'UpdateMinCacheForRow' is invalid in C99
      [-Wimplicit-function-declaration]
            UpdateMinCacheForRow(asMin,i,aafDistMatrix);
            ^
FCluster.c:234:1: warning: control reaches end of non-void function 
[-Wreturn-type]
};
^
FCluster.c:237:1: warning: type specifier missing, defaults to 'int' 
[-Wimplicit-int]
UpdateMinCacheForRow(struct t_Min* asMin,int i,float** aafDistMatrix)
^~~~~~~~~~~~~~~~~~~~
FCluster.c:255:1: warning: control reaches end of non-void function 
[-Wreturn-type]
};
^
FCluster.c:860:3: error: non-void function 'outputCluster' should return a 
value [-Wreturn-type]
  return;
  ^
5 warnings and 1 error generated.
make[1]: *** [FCluster.o] Error 1
make: *** [all] Error 2

```

Original issue reported on code.google.com by `charles....@gmail.com` on 10 May 2013 at 5:35
